# Development environment overrides
replicaCount: 3
env: dev
springProfile: dev

image:
  repository: europe-central2-docker.pkg.dev/project-77fd6584-9134-4b27-9b1/webapp-dev/webapp
  tag: "latest"
  pullPolicy: Always

ingress:
  className: gce
  staticIpName: dev-webapp-lb-ip
  securityPolicy: dev-webapp-waf-policy

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: dev-webapp-sa@project-77fd6584-9134-4b27-9b1.iam.gserviceaccount.com

database:
  host: "10.184.0.3"
  port: 5432
  name: "dev-webapp-db"
  user: "webapp_admin"
  secretManagerKey: "dev-db-password"
