# Production environment overrides
replicaCount: 5
env: prod
springProfile: prod

image:
  repository: europe-central2-docker.pkg.dev/project-77fd6584-9134-4b27-9b1/webapp-prod/webapp
  tag: "1.0.0"
  pullPolicy: IfNotPresent

ingress:
  className: nginx
  host: prod.spring-boot-api.arsh.io

serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: prod-webapp-sa@project-77fd6584-9134-4b27-9b1.iam.gserviceaccount.com

database:
  host: "10.111.0.2"
  port: 5432
  name: "webapp"
  user: "webapp_admin"
  secretManagerKey: "prod-db-password"
