apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "spring-boot-api.fullname" . }}-gcp
    kind: SecretStore
  target:
    name: {{ include "spring-boot-api.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .Values.database.secretManagerKey }}
