apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.service.ports.api }}
          - path: /logs
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.service.ports.logs }}
          - path: /soap
            pathType: Prefix
            backend:
              service:
                name: {{ include "spring-boot-api.fullname" . }}
                port:
                  number: {{ .Values.service.ports.soap }}
