apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 30m
  target:
    name: {{ include "spring-boot-api.fullname" . }}-registry
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GCRAccessToken
          name: {{ include "spring-boot-api.fullname" . }}-gcr
