apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-gcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spring-boot-api.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcpProjectId }}
      auth:
        workloadIdentity:
          clusterLocation: europe-central2-a
          clusterName: {{ .Values.env }}-global-cluster-0
          serviceAccountRef:
            name: {{ include "spring-boot-api.fullname" . }}
